// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZS7kA3tc8a9UoODpvz0ty7LJk2UjuTeQ',
    appId: '1:903573301568:web:ef176ca562f9e2b4c532a5',
    messagingSenderId: '903573301568',
    projectId: 'rastreoproyecto',
    authDomain: 'rastreoproyecto.firebaseapp.com',
    storageBucket: 'rastreoproyecto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdkdwt_B9Xf-XgTK4ZO0slUpVUheX5Nw',
    appId: '1:903573301568:android:321c9a1c606759e5c532a5',
    messagingSenderId: '903573301568',
    projectId: 'rastreoproyecto',
    storageBucket: 'rastreoproyecto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSHIsnCe6gl9PPi1NcjqbMDgOwdtIDco',
    appId: '1:903573301568:ios:56e26e33ec1dbc16c532a5',
    messagingSenderId: '903573301568',
    projectId: 'rastreoproyecto',
    storageBucket: 'rastreoproyecto.appspot.com',
    iosBundleId: 'com.example.apprastreoadministracionproyectorealizado',
  );
}
